### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by morsik** [eventials/django-pjax#9]
Demo always loads whole page, instead of non-refreshable AJAX call.

**Comment by ramiro** [comment]
Which demo? The one linked from the README file? (http://pjax.heroku.com it should be updated to https://pjax.herokuapp.com).

It works for me. Don't forget to read the instructions and tick the 'pjax' checkbox.

**Comment by skrater** [comment]
Fixed link to https://pjax.herokuapp.com 730b039539570a83236315706c54863b1b4981f8
